# Generated by Django 2.2.4 on 2019-10-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191017_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='babybuddy.Account', verbose_name='Account'),
        ),
    ]
