# Generated by Django 2.2.4 on 2019-10-22 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0014_auto_20191022_0409'),
        ('core', '0011_auto_20191017_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-start', '-end'], 'verbose_name': 'Timer', 'verbose_name_plural': 'Timers'},
        ),
        migrations.AddField(
            model_name='timer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='babybuddy.Account', verbose_name='Account'),
        ),
    ]
