# Generated by Django 2.2.4 on 2019-10-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191022_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='complete',
            field=models.BooleanField(default=False, editable=False, verbose_name='Complete'),
        ),
    ]
