# Generated by Django 2.2.4 on 2019-10-23 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timer_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start time'),
        ),
    ]
