# Generated by Django 2.2.4 on 2019-10-25 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='account',
            field=models.ForeignKey(help_text='Select an account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='babybuddy.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='diaperchange',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='diaper_change', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='note',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(help_text='Select an account', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='babybuddy.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(help_text='Instructive message to display with notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Select a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(blank=True, help_text='When would like the notification to stop occuring?', null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency_hours',
            field=models.IntegerField(default=0, help_text='Hours between notificiations', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='intervals',
            field=models.IntegerField(default=1, help_text='Number of subsequent times to issue the notification', verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(help_text='When would like the notification to start occuring?', verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Descriptive title to identify the notification', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Select an account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='babybuddy.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Select a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='tummytime',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='tummy_time', to='core.Child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='child',
            field=models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='core.Child', verbose_name='Child'),
        ),
    ]
