# Generated by Django 2.2.4 on 2019-10-29 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191028_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
