# Generated by Django 2.2.4 on 2019-10-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_timer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.DurationField(default=None, editable=False, null=True, verbose_name='Duration'),
        ),
    ]
