# Generated by Django 2.2.4 on 2019-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191029_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
