# Generated by Django 2.2.6 on 2019-10-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191029_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='send_app_notification',
            field=models.BooleanField(default=True, verbose_name='Send app notification'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Send At'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='send_email_notification',
            field=models.BooleanField(default=False, verbose_name='Send email'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='send_text_notification',
            field=models.BooleanField(default=False, verbose_name='Send text message'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='acknowledged_type',
            field=models.CharField(choices=[('text_message', 'Text Message'), ('email', 'Email'), ('app', 'Web')], max_length=255, verbose_name='Acknowledged Type'),
        ),
    ]
