# Generated by Django 2.2.6 on 2019-10-31 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_auto_20191031_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationevent',
            name='type',
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaper_change', models.BooleanField(default=False)),
                ('feeding', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
                ('temperature_check', models.BooleanField(default=False)),
                ('tummy_time', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('send_text_notification', models.BooleanField(default=False, verbose_name='Send text message')),
                ('send_email_notification', models.BooleanField(default=False, verbose_name='Send email')),
                ('send_app_notification', models.BooleanField(default=True, verbose_name='Send app notification')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Send At')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('child', models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='core.Child', verbose_name='Child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Suggestion')),
            ],
        ),
    ]
