# Generated by Django 2.2.6 on 2019-10-31 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191031_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-start'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 14, 5, 16, 175715, tzinfo=utc), verbose_name='Send At'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['child'], name='child_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['notification'], name='notification_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['send_at'], name='send_at_idx'),
        ),
    ]
