# Generated by Django 2.2.6 on 2019-11-02 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191031_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationevent',
            name='send_app_notification',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='send_email_notification',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='send_text_notification',
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency_hours',
            field=models.IntegerField(default=0, help_text='Hours between notificiations', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='intervals',
            field=models.IntegerField(default=1, help_text='Number of subsequent times to issue the notification', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval'),
        ),
    ]
