# Generated by Django 2.2.6 on 2019-12-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191102_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['complete', '-id'], 'verbose_name': 'Timer', 'verbose_name_plural': 'Timers'},
        ),
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('child', models.ForeignKey(help_text='Select a child', on_delete=django.db.models.deletion.CASCADE, related_name='baths', to='core.Child', verbose_name='Child')),
            ],
            options={
                'verbose_name': 'Bath',
                'verbose_name_plural': 'Baths',
                'ordering': ['-time'],
            },
        ),
    ]
