# Generated by Django 2.2.6 on 2019-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191130_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='units',
            field=models.CharField(choices=[('ounces', 'Ounces'), ('milliliters', 'Milliliters')], default='ounces', max_length=20, verbose_name='Units'),
        ),
        migrations.AddField(
            model_name='weight',
            name='units',
            field=models.CharField(choices=[('pounds', 'Pounds'), ('grams', 'Grams')], default='pounds', max_length=20, verbose_name='Units'),
        ),
    ]
