# Generated by Django 2.2.6 on 2019-12-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20191202_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='units',
            field=models.CharField(choices=[('pounds', 'Pounds'), ('kilograms', 'Kilograms')], default='pounds', max_length=20, verbose_name='Units'),
        ),
    ]
