# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path(
        'children/',
        views.ChildList.as_view(),
        name='child-list'
    ),
    path(
        'children/add/',
        views.ChildAdd.as_view(),
        name='child-add'
    ),
      path(
        'children/<slug:slug>/',
        views.ChildDetail.as_view(),
        name='child'
    ),
    path(
        'children/<slug:slug>/edit/',
        views.ChildUpdateView.as_view(),
        name='child-update'
    ),
    path(
        'children/<slug:slug>/deactivate/',
        views.ChildDeactivateView.as_view(),
        name='child-deactivate'
    ),
    path(
        'children/<slug:slug>/activate/',
        views.ChildActivateView.as_view(),
        name='child-activate'
    ),
    path(
        'children/<slug:slug>/delete/',
        views.ChildDeleteView.as_view(),
        name='child-delete'
    ),

    path(
        'children/<slug:slug>/bath/',
        views.BathAddListView.as_view(),
        name='bath'
    ),

    path(
        'children/<slug:slug>/changes/',
        views.DiaperChangeAddListView.as_view(),
        name='diaperchange'
    ),
    path(
        'children/<slug:slug>/feedings/',
        views.FeedingAddListView.as_view(),
        name='feeding'
    ),
    path(
        'children/<slug:slug>/feedings/info/',
        views.FeedingAddListView.as_view(),
        name='feeding-info'
    ),
    path(
        'children/<slug:slug>/notes/',
        views.NoteAddListView.as_view(),
        name='note'
    ),
    path(
        'children/<slug:slug>/notes/<int:pk>/',
        views.NoteUpdateView.as_view(),
        name='note-update'
    ),
    path(
        'children/<slug:slug>/notes/<int:pk>/delete/',
        views.NoteDeleteView.as_view(),
        name='note-delete'
    ),
    path(
        'notifications/add/',
        views.NotificationAddView.as_view(),
        name='notification-add'
    ),
    path(
        'notifications/',
        views.NotificationsListView.as_view(),
        name='notification-list'
    ),
    path(
        'notifications/<int:pk>/',
        views.NotificationDetailView.as_view(),
        name='notification-detail'
    ),
    path(
        'children/<slug:slug>/sleep/',
        views.SleepAddListView.as_view(),
        name='sleep'
    ),
    path(
        'children/<slug:slug>/temperature/',
        views.TemperatureAddListView.as_view(),
        name='temperature'
    ),
    path(
        'children/<slug:slug>/temperature/<int:pk>/',
        views.TemperatureUpdateView.as_view(),
        name='temperature-update'
    ),
    path(
        'children/<slug:slug>/temperature/<int:pk>/delete/',
        views.TemperatureDeleteView.as_view(),
        name='temperature-delete'
    ),

    path(
        'children/<slug:slug>/timers/',
        views.TimerAddListView.as_view(),
        name='timer'
    ),
    path(
        'timers/',
        views.TimerListView.as_view(),
        name='timer-list'
    ),
    path(
        'timer/add/',
        views.TimerQuickAddView.as_view(),
        name='timer-quick-add'
    ),
    path(
        'timer/<int:pk>/',
        views.TimerDetailView.as_view(),
        name='timer-detail'
    ),
    path(
        'timer/<int:pk>/edit/',
        views.TimerUpdateView.as_view(),
        name='timer-update'
    ),
    path(
        'timer/<int:pk>/delete/',
        views.TimerDeleteView.as_view(),
        name='timer-delete'
    ),
    path(
        'timer/<int:pk>/stop/',
        views.TimerCompleteView.as_view(),
        name='timer-complete'
    ),
    path(
        'children/<slug:slug>/tummy-time/',
        views.TummyTimeAddListView.as_view(),
        name='tummytime'
    ),
    path(
        'children/<slug:slug>/tummy-time/<int:pk>/',
        views.TummyTimeUpdateView.as_view(),
        name='tummytime-update'
    ),
    path(
        'children/<slug:slug>/tummy-time/<int:pk>/delete/',
        views.TummyTimeDeleteView.as_view(),
        name='tummytime-delete'
    ),

    path(
        'children/<slug:slug>/weight/',
        views.WeightAddListView.as_view(),
        name='weight'
    ),
    path(
        'children/<slug:slug>/weight/<int:pk>/',
        views.WeightUpdateView.as_view(),
        name='weight-update'
    ),
    path(
        'children/<slug:slug>/weight/<int:pk>/delete/',
        views.WeightDeleteView.as_view(),
        name='weight-delete'
    ),
]
