# Generated by Django 2.2.4 on 2019-10-17 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
