# Generated by Django 2.2.4 on 2019-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0010_auto_20191017_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
