# Generated by Django 2.2.4 on 2019-10-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('babybuddy', '0011_auto_20191018_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_notifications_enabled',
        ),
        migrations.CreateModel(
            name='AccountMemberSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_notifications_enabled', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('is_payer', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to='babybuddy.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
