# Generated by Django 2.2.4 on 2019-10-22 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0013_auto_20191020_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmembersettings',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['account__name'], 'verbose_name': 'Account Member Settings', 'verbose_name_plural': 'Account Member Settings'},
        ),
        migrations.AlterField(
            model_name='accountmembersettings',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_member_settings', to='babybuddy.Account'),
        ),
        migrations.AlterField(
            model_name='accountmembersettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Email notifications'),
        ),
        migrations.AlterField(
            model_name='accountmembersettings',
            name='phone_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Phone notifications'),
        ),
        migrations.AlterField(
            model_name='accountmembersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_member_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
