# Generated by Django 2.2.6 on 2019-11-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0015_accountmembersettings_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('max_usage', models.IntegerField(default=1)),
                ('months_valid', models.IntegerField(default=1)),
                ('apply_premium', models.BooleanField(default=False)),
                ('apply_additional_member', models.BooleanField(default=False)),
                ('apply_additional_child', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='international format +14155552671 = +[country code][area code][phone]', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AccountPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_promo_codes', to='babybuddy.Account')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_promo_codes', to='babybuddy.PromoCode')),
            ],
        ),
    ]
