# Generated by Django 2.2.6 on 2019-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybuddy', '0016_auto_20191127_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='max_usage_per_account',
            field=models.IntegerField(default=1),
        ),
    ]
